* Generated by Signal Modelling Language
* GAMS is a modelling language and execution environment.
* Solver engines such as PATH, CONOPT, and IPOPT perform numeric computation.

Sets
    sectors / agriculture, manufacturing, services /
    factors / labour, capital /
    households / rural, urban /;

Parameters
    sam_source / 0 /
    elasticity_armington / 2.000000 /
    elasticity_cet / 2.000000 /
    total_activity / 2940.000000 /;

Variables output, price, consumption, imports, exports;

Equations market_clearing, household_income, armington_demand, cet_supply, government_balance, savings_investment_balance;
market_clearing.. output =g= 0;
household_income.. output =g= 0;
armington_demand.. output =g= 0;
cet_supply.. output =g= 0;
government_balance.. output =g= 0;
savings_investment_balance.. output =g= 0;

Scalars
    shock_increase_vat / 0.020000 /
    shock_productivity_growth / 0.050000 /;

option nlp=path;
option mcp=path;
Model kenya_cge / all /;
Solve kenya_cge using CNS;
Display output, price, consumption, imports, exports;
execute_unload "outputs/results.gdx";
