*-#### ASSIGN THE PERCENTAGE CHANGES
SCALAgRes("sERX",%resElem1%)                        = resultAg("%resType%",'sERX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sCPI",%resElem1%)                        = resultAg("%resType%",'sCPI','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sPPI",%resElem1%)                        = resultAg("%resType%",'sPPI','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sMTAX",%resElem1%)                       = resultAg("%resType%",'sMTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sETAX",%resElem1%)                       = resultAg("%resType%",'sETAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sSTAX",%resElem1%)                       = resultAg("%resType%",'sSTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sEXTAX",%resElem1%)                      = resultAg("%resType%",'sEXTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sVTAX",%resElem1%)                       = resultAg("%resType%",'sVTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sITAX",%resElem1%)                       = resultAg("%resType%",'sITAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sITAXA",%resElem1%)                      = resultAg("%resType%",'sITAXA','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sFTAX",%resElem1%)                       = resultAg("%resType%",'sFTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sDTAX",%resElem1%)                       = resultAg("%resType%",'sDTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sFYTAX",%resElem1%)                      = resultAg("%resType%",'sFYTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sINTAX",%resElem1%)                      = resultAg("%resType%",'sINTAX','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sYG",%resElem1%)                         = resultAg("%resType%",'sYG','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sEG",%resElem1%)                         = resultAg("%resType%",'sEG','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sINVEST",%resElem1%)                     = resultAg("%resType%",'sINVEST','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sTOTSAV",%resElem1%)                     = resultAg("%resType%",'sTOTSAV','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sKAPGOV",%resElem1%)                     = resultAg("%resType%",'sKAPGOV','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sKAPWOR",%resElem1%)                     = resultAg("%resType%",'sKAPWOR','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sVFDOMD",%resElem1%)                     = resultAg("%resType%",'sVFDOMD','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sVGD",%resElem1%)                        = resultAg("%resType%",'sVGD','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sINVESTSH",%resElem1%)                   = resultAg("%resType%",'sINVESTSH','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sVGDSH",%resElem1%)                      = resultAg("%resType%",'sVGDSH','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sGDP",%resElem1%)                        = resultAg("%resType%",'sGDP','NaN','NaN','NaN','NaN',%resElem1%);
SCALAgRes("sWALRAS",%resElem1%)                     = resultAg("%resType%",'sWALRAS','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aADXADJ",%resElem1%)                      = resultAg("%resType%",'aADXADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDADX",%resElem1%)                        = resultAg("%resType%",'aDADX','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aADVAADJ",%resElem1%)                     = resultAg("%resType%",'aADVAADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDADVA",%resElem1%)                       = resultAg("%resType%",'aDADVA','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aQEDADJ",%resElem1%)                      = resultAg("%resType%",'aQEDADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aHEADJ",%resElem1%)                       = resultAg("%resType%",'aHEADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTEADJ",%resElem1%)                       = resultAg("%resType%",'aTEADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTMADJ",%resElem1%)                       = resultAg("%resType%",'aTMADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTSADJ",%resElem1%)                       = resultAg("%resType%",'aTSADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTEXADJ",%resElem1%)                      = resultAg("%resType%",'aTEXADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTVADJ",%resElem1%)                       = resultAg("%resType%",'aTVADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTXADJ",%resElem1%)                       = resultAg("%resType%",'aTXADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTFADJ",%resElem1%)                       = resultAg("%resType%",'aTFADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTYFADJ",%resElem1%)                      = resultAg("%resType%",'aTYFADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTYHADJ",%resElem1%)                      = resultAg("%resType%",'aTYHADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTYADJ",%resElem1%)                       = resultAg("%resType%",'aTYADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTYEADJ",%resElem1%)                      = resultAg("%resType%",'aTYEADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aTINADJ",%resElem1%)                      = resultAg("%resType%",'aTINADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTE",%resElem1%)                         = resultAg("%resType%",'aDTE','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTM",%resElem1%)                         = resultAg("%resType%",'aDTM','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTS",%resElem1%)                         = resultAg("%resType%",'aDTS','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTEX",%resElem1%)                        = resultAg("%resType%",'aDTEX','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTV",%resElem1%)                         = resultAg("%resType%",'aDTV','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTX",%resElem1%)                         = resultAg("%resType%",'aDTX','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTXA",%resElem1%)                        = resultAg("%resType%",'aDTXA','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTF",%resElem1%)                         = resultAg("%resType%",'aDTF','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTYF",%resElem1%)                        = resultAg("%resType%",'aDTYF','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTYH",%resElem1%)                        = resultAg("%resType%",'aDTYH','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTY",%resElem1%)                         = resultAg("%resType%",'aDTY','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTYE",%resElem1%)                        = resultAg("%resType%",'aDTYE','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDTIN",%resElem1%)                        = resultAg("%resType%",'aDTIN','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aQGDADJ",%resElem1%)                      = resultAg("%resType%",'aQGDADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aHGADJ",%resElem1%)                       = resultAg("%resType%",'aHGADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDHOGOV",%resElem1%)                      = resultAg("%resType%",'aDHOGOV','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aEGADJ",%resElem1%)                       = resultAg("%resType%",'aEGADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aSADJ",%resElem1%)                        = resultAg("%resType%",'aSADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aSHADJ",%resElem1%)                       = resultAg("%resType%",'aSHADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aSEADJ",%resElem1%)                       = resultAg("%resType%",'aSEADJ','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDSHH",%resElem1%)                        = resultAg("%resType%",'aDSHH','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDS",%resElem1%)                          = resultAg("%resType%",'aDS','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aDSEN",%resElem1%)                        = resultAg("%resType%",'aDSEN','NaN','NaN','NaN','NaN',%resElem1%);
ADJAgRes("aIADJ",%resElem1%)                        = resultAg("%resType%",'aIADJ','NaN','NaN','NaN','NaN',%resElem1%);
ERAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'sER',sacAg,'NaN','NaN','NaN',%resElem1%);
KAPREGAgRes(sacAg,%resElem1%)                       = resultAg("%resType%",'sKAPREG',sacAg,'NaN','NaN','NaN',%resElem1%);
PWEAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PWE',sacAg,'NaN','NaN','NaN',%resElem1%);
PEAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'PE',sacAg,'NaN','NaN','NaN',%resElem1%);
PERAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'PER',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PDAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'PD',sacAg,'NaN','NaN','NaN',%resElem1%);
QEAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'QE',sacAg,'NaN','NaN','NaN',%resElem1%);
QERAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'QER',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QDAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'QD',sacAg,'NaN','NaN','NaN',%resElem1%);
PWMAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PWM',sacAg,'NaN','NaN','NaN',%resElem1%);
PMAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'PM',sacAg,'NaN','NaN','NaN',%resElem1%);
PMRAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'PMR',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QMAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'QM',sacAg,'NaN','NaN','NaN',%resElem1%);
QMRAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'QMR',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QQAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'QQ',sacAg,'NaN','NaN','NaN',%resElem1%);
PTTAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PTT',sacAg,'NaN','NaN','NaN',%resElem1%);
QTTAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'QTT',sacAg,'NaN','NaN','NaN',%resElem1%);
QTTDAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'QTTD',sacAg,'NaN','NaN','NaN',%resElem1%);
PQSAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PQS',sacAg,'NaN','NaN','NaN',%resElem1%);
PQDAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PQD',sacAg,'NaN','NaN','NaN',%resElem1%);
PQCDAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'PQCD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PXAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'PX',sacAg,'NaN','NaN','NaN',%resElem1%);
PVAAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PVA',sacAg,'NaN','NaN','NaN',%resElem1%);
PINTAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'PINT',sacAg,'NaN','NaN','NaN',%resElem1%);
ADXAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'ADX',sacAg,'NaN','NaN','NaN',%resElem1%);
ADAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'AD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
ADFDAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'ADFD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
ADFHAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'ADFH',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QXAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'QX',sacAg,'NaN','NaN','NaN',%resElem1%);
QVAAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'QVA',sacAg,'NaN','NaN','NaN',%resElem1%);
VVAAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'VVA',sacAg,'NaN','NaN','NaN',%resElem1%);
QINTAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'QINT',sacAg,'NaN','NaN','NaN',%resElem1%);
ADVAAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'ADVA',sacAg,'NaN','NaN','NaN',%resElem1%);
WFAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'WF',sacAg,'NaN','NaN','NaN',%resElem1%);
WFAAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'WFA',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PQDDISTAgRes(sacAg,sacAgp,%resElem1%)               = resultAg("%resType%",'PQDDIST',sacAg,sacAgp,'NaN','NaN',%resElem1%);
FDAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'FD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
FSAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'FS',sacAg,'NaN','NaN','NaN',%resElem1%);
UNEMPAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'UNEMP',sacAg,'NaN','NaN','NaN',%resElem1%);
FSIAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'FSI',sacAg,sacAgp,'NaN','NaN',%resElem1%);
FSILAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'FSIL',sacAg,sacAgp,'NaN','NaN',%resElem1%);
FSIMAgRes(sacAg,sacAgp,sacAgpp,sacAgppp,%resElem1%) = resultAg("%resType%",'FSIM',sacAg,sacAgp,sacAgpp,sacAgppp,%resElem1%);
FMIGDRVAgRes(sacAg,sacAgp,%resElem1%)               = resultAg("%resType%",'FMIGDRV',sacAg,sacAgp,'NaN','NaN',%resElem1%);
HMIGDRVAgRes(sacAg,sacAgp,%resElem1%)               = resultAg("%resType%",'HMIGDRV',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PMIGDRVAgRes(sacAg,sacAgp,%resElem1%)               = resultAg("%resType%",'PMIGDRV',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QINTDAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'QINTD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PXCAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'PXC',sacAg,'NaN','NaN','NaN',%resElem1%);
QXCAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'QXC',sacAg,'NaN','NaN','NaN',%resElem1%);
IOQXACQXVAgRes(sacAg,sacAgp,%resElem1%)             = resultAg("%resType%",'IOQXACQXV',sacAg,sacAgp,'NaN','NaN',%resElem1%);
PXACAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'PXAC',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QXACAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'QXAC',sacAg,sacAgp,'NaN','NaN',%resElem1%);
YFAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'YF',sacAg,'NaN','NaN','NaN',%resElem1%);
YFDISPAgRes(sacAg,%resElem1%)                       = resultAg("%resType%",'YFDISP',sacAg,'NaN','NaN','NaN',%resElem1%);
YFINSAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'YFINS',sacAg,'NaN','NaN','NaN',%resElem1%);
FSISHAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'FSISH',sacAg,sacAgp,'NaN','NaN',%resElem1%);
INSVAAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'INSVA',sacAg,sacAgp,'NaN','NaN',%resElem1%);
YHAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'YH',sacAg,'NaN','NaN','NaN',%resElem1%);
HOGOVAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'HOGOV',sacAg,'NaN','NaN','NaN',%resElem1%);
HOHOAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'HOHO',sacAg,sacAgp,'NaN','NaN',%resElem1%);
HOWORAgRes(sacAg,sacAgp,%resElem1%)                  = resultAg("%resType%",'HOWOR',sacAg,sacAgp,'NaN','NaN',%resElem1%);
HEXPAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'HEXP',sacAg,'NaN','NaN','NaN',%resElem1%);
QCDAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'QCD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QCD2AgRes(sacAg,sacAgp,sacAgpp,%resElem1%)          = resultAg("%resType%",'QCD2',sacAg,sacAgp,sacAgpp,'NaN',%resElem1%);
YMIGRAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'YMIGR',sacAg,sacAgp,'NaN','NaN',%resElem1%);
WMIGRAgRes(sacAg,sacAgp,sacAgpp,%resElem1%)         = resultAg("%resType%",'WMIGR',sacAg,sacAgp,sacAgpp,'NaN',%resElem1%);
YEAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'YE',sacAg,'NaN','NaN','NaN',%resElem1%);
HOENTAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'HOENT',sacAg,sacAgp,'NaN','NaN',%resElem1%);
GOVENTAgRes(sacAg,%resElem1%)                       = resultAg("%resType%",'GOVENT',sacAg,'NaN','NaN','NaN',%resElem1%);
QEDAgRes(sacAg,sacAgp,%resElem1%)                   = resultAg("%resType%",'QED',sacAg,sacAgp,'NaN','NaN',%resElem1%);
VEDAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'VED',sacAg,'NaN','NaN','NaN',%resElem1%);
TEAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'TE',sacAg,sacAgp,'NaN','NaN',%resElem1%);
TMAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'TM',sacAg,sacAgp,'NaN','NaN',%resElem1%);
TSAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'TS',sacAg,'NaN','NaN','NaN',%resElem1%);
TVAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'TV',sacAg,'NaN','NaN','NaN',%resElem1%);
TEXAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TEX',sacAg,'NaN','NaN','NaN',%resElem1%);
TXAgRes(sacAg,%resElem1%)                           = resultAg("%resType%",'TX',sacAg,'NaN','NaN','NaN',%resElem1%);
TXAAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TXA',sacAg,'NaN','NaN','NaN',%resElem1%);
TFAgRes(sacAg,sacAgp,%resElem1%)                    = resultAg("%resType%",'TF',sacAg,sacAgp,'NaN','NaN',%resElem1%);
TYFAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TYF',sacAg,'NaN','NaN','NaN',%resElem1%);
TYHAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TYH',sacAg,'NaN','NaN','NaN',%resElem1%);
TYEAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TYE',sacAg,'NaN','NaN','NaN',%resElem1%);
TINAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'TIN',sacAg,'NaN','NaN','NaN',%resElem1%);
QGDAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'QGD',sacAg,'NaN','NaN','NaN',%resElem1%);
SHHAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'SHH',sacAg,'NaN','NaN','NaN',%resElem1%);
SENAgRes(sacAg,%resElem1%)                          = resultAg("%resType%",'SEN',sacAg,'NaN','NaN','NaN',%resElem1%);
QINVDAgRes(sacAg,sacAgp,%resElem1%)                 = resultAg("%resType%",'QINVD',sacAg,sacAgp,'NaN','NaN',%resElem1%);
QINVAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'QINV',sacAg,'NaN','NaN','NaN',%resElem1%);
INVSH_IAgRes(sacAg,%resElem1%)                      = resultAg("%resType%",'INVSH_I',sacAg,'NaN','NaN','NaN',%resElem1%);
YFWORAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'YFWOR',sacAg,'NaN','NaN','NaN',%resElem1%);
VEDSHAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'VEDSH',sacAg,'NaN','NaN','NaN',%resElem1%);
*SolRepAgRes('MODEL-STAT',%resElem1%)                = resultAg("Level",'MODEL-STAT','NaN','NaN','NaN','NaN',%resElem1%);
*SolRepAgRes('SOLVE-STAT',%resElem1%)                = resultAg("Level",'SOLVE-STAT','NaN','NaN','NaN','NaN',%resElem1%);
*SolRepAgRes('NUM-REDEFQ',%resElem1%)                = resultAg("Level",'NUM-REDEFQ','NaN','NaN','NaN','NaN',%resElem1%);
*SolRepAgRes('iterUsd',%resElem1%)                   = resultAg("Level",'iterUsd','NaN','NaN','NaN','NaN',%resElem1%);
AgBuRecurrAgRes(sacAg,%resElem1%)                   = resultAg("%resType%",'AgBuRecurr',sacAg,'NaN','NaN','NaN',%resElem1%);
AgBuInvestAgRes(sacAg,%resElem1%)                   = resultAg("%resType%",'AgBuInvest',sacAg,'NaN','NaN','NaN',%resElem1%);
AgBuInpSubAgRes(sacAg,sacAgp,%resElem1%)            = resultAg("%resType%",'AgBuInpSub',sacAg,sacAgp,'NaN','NaN',%resElem1%);
AgBuOutSubAgRes(sacAg,%resElem1%)                   = resultAg("%resType%",'AgBuOutSub',sacAg,'NaN','NaN','NaN',%resElem1%);
AgBuComSubAgRes(sacAg,sacagp,%resElem1%)             = resultAg("%resType%",'AgBuComSub',sacAg,sacagp,'NaN','NaN',%resElem1%);
AgBuIncSubAgRes(sacAg,%resElem1%)                   = resultAg("%resType%",'AgBuIncSub',sacAg,'NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("Recurr",%resElem1%)                   = resultAg("%resType%",'AgBuTotRecurr','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("Invest",%resElem1%)                   = resultAg("%resType%",'AgBuTotInvest','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("InpSub",%resElem1%)                   = resultAg("%resType%",'AgBuTotInpSub','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("OutSub",%resElem1%)                   = resultAg("%resType%",'AgBuTotOutSub','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("ComSub",%resElem1%)                   = resultAg("%resType%",'AgBuTotComSub','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("IncSub",%resElem1%)                   = resultAg("%resType%",'AgBuTotIncSub','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("Total",%resElem1%)                    = resultAg("%resType%",'AgBuTotalx','NaN','NaN','NaN','NaN',%resElem1%);
AgBuTotAgRes("Share",%resElem1%)                    = resultAg("%resType%",'AgBuTotShr','NaN','NaN','NaN','NaN',%resElem1%);

EXTENSAgRes(sacAg,sacAgp,%resElem1%)                = resultAg("%resType%",'EXTENS',sacAg,sacAgp,'NaN','NaN',%resElem1%);
ADFExtAgRes(sacAg,%resElem1%)                       = resultAg("%resType%",'ADFExt',sacAg,'NaN','NaN','NaN',%resElem1%);
EDUCAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'EDUC',sacAg,'NaN','NaN','NaN',%resElem1%);
HEALAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'HEAL',sacAg,'NaN','NaN','NaN',%resElem1%);
DEATHAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'DEATH',sacAg,'NaN','NaN','NaN',%resElem1%);
BIRTHAgRes(sacAg,%resElem1%)                        = resultAg("%resType%",'BIRTH',sacAg,'NaN','NaN','NaN',%resElem1%);
POPNAgRes(sacAg,%resElem1%)                         = resultAg("%resType%",'POPN',sacAg,'NaN','NaN','NaN',%resElem1%);
POPCHNGAgRes(sacAg,%resElem1%)                      = resultAg("%resType%",'POPCHNG',sacAg,'NaN','NaN','NaN',%resElem1%);


Execute_Unload  '%resultF%/%mode%_%exp%_res%resType%Aggr.gdx',
SCALAgRes
ADJAgRes
ERAgRes
KAPREGAgRes
PWEAgRes
PEAgRes
PERAgRes
PDAgRes
QEAgRes
QERAgRes
QDAgRes
PWMAgRes
PMAgRes
PMRAgRes
QMAgRes
QMRAgRes
QQAgRes
PTTAgRes
QTTAgRes
QTTDAgRes
PQSAgRes
PQDAgRes
PQCDAgRes
PXAgRes
PVAAgRes
PINTAgRes
ADXAgRes
ADAgRes
ADFDAgRes
ADFHAgRes
QXAgRes
QVAAgRes
VVAAgRes
QINTAgRes
ADVAAgRes
WFAgRes
WFAAgRes
PQDDISTAgRes
FDAgRes
FSAgRes
UNEMPAgRes
FSIAgRes
FSILAgRes
FSIMAgRes
FMIGDRVAgRes
HMIGDRVAgRes
PMIGDRVAgRes
QINTDAgRes
PXCAgRes
QXCAgRes
IOQXACQXVAgRes
PXACAgRes
QXACAgRes
YFAgRes
YFDISPAgRes
YFINSAgRes
FSISHAgRes
INSVAAgRes
YHAgRes
HOHOAgRes
HOWORAgRes
HEXPAgRes
QCDAgRes
QCD2AgRes
YMIGRAgRes
WMIGRAgRes
YEAgRes
HOENTAgRes
GOVENTAgRes
QEDAgRes
VEDAgRes
TEAgRes
TMAgRes
TSAgRes
TVAgRes
TEXAgRes
TXAgRes
TXAAgRes
TFAgRes
TYFAgRes
TYHAgRes
TYEAgRes
TINAgRes
QGDAgRes
SHHAgRes
SENAgRes
QINVDAgRes
QINVAgRes
INVSH_IAgRes
YFWORAgRes
VEDSHAgRes
EXTENSAgRes
ADFExtAgRes
EDUCAgRes
HEALAgRes
DEATHAgRes
BIRTHAgRes
POPNAgRes
POPCHNGAgRes
*SolRepAgRes
AgBuRecurrAgRes
AgBuInvestAgRes
AgBuInpSubAgRes
AgBuOutSubAgRes
AgBuComSubAgRes
AgBuIncSubAgRes
AgBuTotAgRes

;
