SET
resType
/
Level         Results in levels
perc          Percentage Change from the first period
PerBase       Percentage differece from the Baseline
DiffBase      Level difference from the Baseline
YearPerc      Percentage change from previous year
Share         Share
ShareGDP      Share in GDP
ShareABS      Share in Absorbtion
perFert
PerBaseLastYear Perecntage change from base in the Last period

/

varType
/
Nominal      Nominal (current year prices)
Real         Real (with baseyear prices)
/
resvar        Variables
/
SAM           "Result SAMs"
TOTALSCHECKP  "sum of abs value of differences as fraction of SAM total"
SCAL          "table of scalar results"
ADJ           "table of adjuster results"
sER           "Exchange Rate"
sERX          "Exchange Rate"
sCPI          "Consumer price index"
sPPI          "Producer Price Index"
sMTAX         "Tariff revenue"
sETAX         "Export tax revenue"
sSTAX         "Sales tax revenue"
sQSTAX        ""
sEXTAX        "Excise tax revenue"
sVTAX         "Value added tax revenue"
sITAX         "Indirect tax revenue"
sITAXA        "Indirect tax revenue on agriculture"
sASUBEQV      ""
sFTAX         "Factor use tax revenue"
sDTAX         "Direct Income tax revenue"
sFYTAX        "Factor Income tax revenue"
sINTAX        "Intermediate input tax reveneu"
sYG           "Government income"
sEG           "Government Expenditure"
sGBUDG        "Government budget for current spendings and investments"
sINVEST       "Investment"
sTOTSAV       "Saving"
sKAPGOV       "Government Saving"
sKAPWOR       "Foreing Saving"
sKAPREG       "Foreing Saving"
sVFDOMD       "Value of final domestic demand"
sVGD          "Government consumption expenditure"
sINVESTSH     "Share of investment in total final domestic demand"
sVGDSH        "Government consumption share"
sGDP          "Gross Domestic Product"
sRGDP         "Real Gross Domestic Product"
sRGDPFC       "Real Gross Domestic Product at Factor Cost"
sWALRAS       "Walras residual"
aADXADJ       "Scaling Factor for Shift parameter on CES functions for QX"
aDADX         "Partial scaling factor for Shift parameter on CES functions for QX"
aADVAADJ      "Shift parameter for CES production functions for QVA"
aDADVA        "Scaling Factor for Shift parameter on CES functions for QVA"
aQEDADJ       "Enterprise demand volume Scaling Factor"
aHEADJ        "Scaling factor for enterprise transfers to households"
aTEADJ        "Export subsidy Scaling Factor"
aTMADJ        "Tarrif rate Scaling Factor"
aTSADJ        "Sales tax rate scaling factor"
aTQSADJ       ""
aTVADJ        "Value added tax rate scaling factor"
aTEXADJ       "Excise tax rate scaling factor"
aTXADJ        "Indirect Tax Scaling Factor"
aTFADJ        "Factor Use Tax Scaling Factor"
aTYFADJ       "Factor Tax Scaling Factor"
aTYHADJ       "Household Income Tax Scaling Factor"
aTYADJ        "Household and Enterprise Income Tax Scaling Factor"
aTYEADJ       "Enterprise income tax Scaling Factor"
aTINADJ       "Intermediate input tax Scaling Factor"
aTHCADJ       "Household specific commodity tax Scaling Factor"
aDTE          "Partial Export tax rate scaling factor"
aDTM          "Partial Tariff rate scaling factor"
aDTS          "Partial Sales tax rate scaling factor"
aDTQS         ""
aDTV          "Partial value added tax rate scaling factor"
aDTEX         "Partial Excise tax rate scaling factor"
aDTX          "Partial Indirect tax rate scaling factor"
aDTXA         "Partial Indirect tax rate scaling factor"
aDTF          "Uniform adjustment to factor use tax by activity"
aDTYF         "Partial direct tax on factor rate scaling factor"
aDTYH         "Partial direct tax on household rate scaling factor"
aDTY          "Partial direct tax on hold and enterprise rate scaling factor"
aDTYE         "Partial direct tax on enterprise rate scaling factor"
aDTIN         "Partial intermediate input tax scaling factor"
aDTHC         "Partial Household specific commodity tax"
aQGDADJ       "Government consumption demand scaling factor"
aQGDADJceh    "Government spending adjuster for education and health commodities in agricultural budg"
aQGDADJoth    "Government spending adjuster for other commodities in general budget"
aQGDADJext    "Government spending adjuster for extension commodities in agricultural budget"
QGDADJc       "Commodity level government spending adjuster"
aHGADJ        "Scaling factor for government transfers to URB households"
aDHOGOV       "Scaling factor for government transfers to URB households"
aEGADJ        "Transfers to enterprises by government Scaling Factor"
aSADJ         "Savings rate scaling factor for BOTH households and enterpriseste"
aSHADJ        "Savings rate scaling factor for households"
aSEADJ        "Savings rate scaling factor for enterprises"
aDSHH         "Partial household savings rate scaling factor"
aDS           "Partial household and enterprise savings rate scaling factor"
aDSEN         "Partial enterprise savings rate scaling factor"
aIADJ         "Investment scaling factor for investment of type i"
PWE           "World price of exports in dollars"
PWSE           "World price of exports in dollars"
PE            "Domestic price of exports by activity a"
PER           "Domestic price of exports by activity a from region r"
PD            "Consumer price for domestic supply of commodity c"
QE            "Domestic output exported by commodity c"
QER           "Domestic output exported by commodity c from region r"
QD            "Domestic demand for commodity c"
PWM           "World price of imports in dollars"
PM            "Domestic price of competitive imports of commodity c"
PMR           "Domestic price of competitive imports of commodity c from region w"
QM            "Imports of commodity c"
QMR           "Imports of commodity c from region w"
QQ            "Supply of composite commodity c"
IOQTTQQ       "Trade margins"
PTT           "Price of trade and transport margin m"
QTT           "Quantity of trade and transport margin m"
QTTD          "Intermediate input use for trade and transport margin m"
PQS           "Supply price of composite commodity c"
PQD           "Purchaser price of composite commodity c"
PQCD          "Purchaser price of aggregate commodity cag by h"
PQC           "price paid by consumers for consumed commodities"
PX            "Composite price of output by activity a"
PVA           "Value added price for activity a"
PINT          "Price of aggregate intermediate input"
ADX           "Shift parameter for CES production functions for QX"
AD            "Total efficiency impact ADFD*(1+ADFH))"
ADFD          "Shift parameter for factor and activity specific efficiency"
ADFH          "Shift parameter for factor and activity specific efficiency"
QX            "Domestic production by activity a"
QVA           "Quantity of aggregate value added for level 1 production"
VVA           "Value of aggregate value added calculated from natural factor values"
QINT          "Aggregate quantity of intermediates used by activity a"
ADVA          "Shift parameter for CES production functions for QVA"
WF            "Price of factor f"
WFDIST        "Sectoral proportion for factor prices"
WFA           "Sectoral factor prices (WFxWFDIST)"
PQDDIST       "Price distribution parameter for factors coming from int inps"
FD            "Demand for factor f by activity a"
FS            "Supply of factor f"
FSI           "Factor supplies from institution ins by factor f"
FSIL          "Factor supply for leisure"
FSIM          "Number of factors to f from f by ins"
MIGCONS       "constant part of Share of population migrating"
SHMIG          Share of population migrating
URBNRATE      Share of urban population in total population
UNEMP         "Unemployment"
UNEMPRATE     "Unemployment rate"
COMTOTSH      "Share of commodity c in total commodity demand"
VQCD          "Value of domestic output for the domestic market"
FMIGDRV       "Migration driver from fp to f"
HMIGDRV       "Migration driver from insp to ins"
PMIGDRV       "Migration driver from insp to ins due to public spending"
QINTD         "Demand for intermediate inputs by commodity"
PXC           "Producer price of composite domestic output"
QXC           "Domestic production by commodity c"
IOQXACQXV     "Share of commodity c in output by activity a"
PXAC          "Activity commodity prices"
QXAC          "Domestic commodity output by each activity"
YF            "Income to factor f"
YFDISP        "Factor income for distribution after depreciation"
YFINS         "Factor income for distribution to domestic non govt institutions"
FSISH         "Shares of factor f supplied by institution ins"
INSVA         "Factor income after deprecn distribution to institn ins"
YH            "Income to household h"
HOGOV         "Government transfers to household h"
HOHO          "Inter household transfer"
HOWOR         "Transfer to HH from ROW"
HEXP          "Household consumption expenditure"
QCD           "Household consumption by commodity c"
QCD2          "Household consumption by com'dy cces used in com'dy cag"
QCDTotal      "Household consumption -by all comm'dy"
YMIGR         "household migration trigger is institution income"
WMIGR         "Wage ratio for factor mobility"
YE            "Enterprise incomes"
HOENT         "Household Income from enterprise e"
GOVENT        "Government income from enterprise e"
QED           "Enterprise consumption by commodity c"
VED           "Value of enterprise e consumption expenditure"
TE            "Export taxes on exported commy c"
TM            "Tariff rates on imported commy c"
TS            "Sales tax rate"
TQS           "Quantity Sales tax rate"
TV            "Value added tax rate"
TEX           "Excise tax rate"
TX            "Indirect tax rate"
TXA           "Indirect tax rate"
TF            "Tax rate on factor use"
TYF           "Direct tax rate on factor income"
TYH           "Direct tax rate on households"
TYE           "Direct tax rate on enterprises"
TIN           "Int inp tax on activity a"
THC           "Household specific commodity tax (for food aid)"
QGD           "Government consumption demand by commodity c"
AgBuRecurr    "Recurrent budget"
AgBuInvest    "Investment budget"
AgBuInpSub    "Input subsidy budget"
AgBuRevFund   "Revolving Fund budget"
AgBuOutSub    "Output subsidy budget"
AgBuComSub    "Commodity subsidies (i.e. food aid)"
AgBuIncSub    "Income subsidies & transfers"
AgBuTotRecurr "Total Recurrent budget"
AgBuTotInvest "Total Investment budget"
AgBuTotInpSub "Total Input subsidy budget"
AgBuTotOutSub "Total Output subsidy budget"
AgBuTotComSub "Total Output subsidy budget"
AgBuTotIncSub "Total Output subsidy budget"
AgBuTOTALx    "Total agricultural budget"
AgBuTOTShr    "Share of agricultural budget in total budget"
SHH           "Household savings rates"
SEN           "Enterprise savings rates"
QINVD         "Investment demand by commodity c"
QINV          "Investment volume by investment type i"
INVSH_I       "Shares of savings to investment of type i"
YFWOR         "Foreign factor income"
VEDSH         "Value share of Ent consumption in total final domestic demand"
EXTENS        "Extension services consumption"
ADFExt        "Change in factor productivity due to extension services"
EDUC          "Education spending per HH"
HEAL          "Health spending per HH"
BRATE         "Birth rate"
DRATE         "Death rate"
DEATH         "Number of deaths"
BIRTH         "Number of births"
POPN          "Demographic structure by age only"
POPCHNG       "change in population due to deaths and births"

CO2EM_Q       "CO2 emissions by activities from use of fossil energy inputs"
CO2EM_H       "CO2 emissions by households from consumption of fossil energy goods"
CO2EMIS_Q     "Total CO2 emissions from energy use by activities"
CO2EMIS_H     "Total CO2 emissions from energy use by households"
CO2EMIS       "Total CO2 emissions from combustion"

NCO2EM_Q      "Non-combustive emissions  by activity"
NCO2EM_FS     "Non-combustive emission based on fossil fuel combustion in production"
NCO2EM_IO     "Process non-combustive emissions based on intermediate demand"
NCO2EM_EN     "Non-combustive emissions based on factor use"
NCO2EM_H      "Non-combustive emissions  by households"
NCO2EM_A_SUM  "Non-combustive emissions total by activity" 
NCO2EM_SUM    "Non-combustive emissions" 
GHGEM         "Total GHG emissions"

NCO2EM_FS_SUM
NCO2EM_IO_SUM
NCO2EM_EN_SUM
NCO2EM_H_SUM

NutVal        "Nutrition Values"
MODEL-STAT    "model status"
SOLVE-STAT    "solver status"
NUM-REDEFQ    "number of redefined equations"
iterUsd       "number of iterations"
/


adjresElem        adjuster results
/
aTEADJ        Export subsidy Scaling Factor
aTMADJ        Tarrif rate Scaling Factor
aTSADJ        Sales tax rate scaling factor
aTVADJ        Value added tax rate scaling factor
aTEXADJ        Excise tax rate scaling factor
aTXADJ        Indirect Tax Scaling Factor
aTFADJ        Factor Use Tax Scaling Factor
aTYFADJ        Factor Tax Scaling Factor
aTYHADJ        Household Income Tax Scaling Factor
aTYADJ        Household and Enterprise Income Tax Scaling Factor
aTYEADJ        Enterprise income tax Scaling Factor
aTINADJ        Int Inp Tax
aTHCADJ        HH spec comm tax (e.g. food aid)
aDTE        Partial Export tax rate scaling factor
aDTM        Partial Tariff rate scaling factor
aDTS        Partial Sales tax rate scaling factor
aDTV        Partial value added tax rate scaling factor
aDTEX        Partial Excise tax rate scaling factor
aDTX        Partial Indirect tax rate scaling factor
aDTXA        Partial Indirect tax rate scaling factor
aDTF        Uniform adjustment to factor use tax by activity
aDTYF        Partial direct tax on factor rate scaling factor
aDTYH        Partial direct tax on household rate scaling factor
aDTY        Partial direct tax on h'hold and enterprise rate scaling factor
aDTYE        Partial direct tax on enterprise rate scaling factor
aDTIN        Partial  tax on int input scaling factor
aDTHC        Partial HH spec comm tax (e.g. food aid)
aSADJ        Savings rate scaling factor
aSHADJ        Households savings rate scaling factor
aSEADJ        Households savings rate scaling factor
aDSHH        Partial household savings rate scaling factor
aDS        Partial household and enterprise savings rate scaling factor
aDSEN        Partial enterprise savings rate scaling factor
aIADJ        Investment scaling factor
aQGDADJ        Government consumption demand scaling factor
aQGDADJceh    "Government spending adjuster for education and health commodities in agricultural budg"
aQGDADJoth    "Government spending adjuster for other commodities in general budget"
aQGDADJext    "Government spending adjuster for extension commodities in agricultural budget"
aQEDADJ        Enterprise demand volume Scaling Factor
aHGADJ        Scaling factor for govt transfers to households
aDHOGOV       Partial Scaling factor for govt transfers to households
aEGADJ        Transfers to enterprises by govt Scaling Factor
aHEADJ        Scaling factor for ent transfers to hhlds
aADXADJ        Scaling Factor for Shift parameter on CES functions for QX
aDADX        Partial scaling factor for Shift parameter on CES functions for QX
aADVAADJ        Scaling Factor for Shift parameter on CES functions for QVA
aDADVA        Partial scaling factor for Shift parameter on CES functions for QVA
/

scalresElem        scalar results
/
sER              Exchange rate (domestic per world unit)
sERX             Exchange rate (domestic per world unit)
sCPI             Consumer price index
sPPI             Producer (domestic) price index
sMTAX            Tariff revenue
sETAX            Export tax revenue
sVTAX            Value added tax revenue
sDTAX            Direct Income tax revenue
sFYTAX           Factor Income tax revenue
sITAX            Indirect tax revenue
sITAXA           Indirect tax revenue on agriculture
sSTAX            Sales tax revenue
sFTAX            Factor use tax revenue
sEXTAX           Excise tax revenue
sINTAX           Int Inp Tax
sINVEST          Total investment expenditure
sTOTSAV          Total savings
sYG              Government income
sEG              Expenditure by government
sGBUDG           Government budget for current spendings and investments
sVGD             Value of Government consumption expenditure
sKAPGOV          Government Savings
sKAPWOR          Current account balance
sVFDOMD          Value of final domestic demand
sINVESTSH        Val share of inv in total final dom demand
sVGDSH           Val share of gov in total final dom demand
sGDP             GDP from Expenditures
sRGDP            Real Gross Domestic Product
sRGDPFC          Real Gross Domestic Product at Factor Cost
sWALRAS          Slack variable for Walras's Law
MODEL-STAT       model status
SOLVE-STAT       solver status
NUM-REDEFQ       number of redefined equations
iterUsd          number of iterations
/

stab1        results tab 1
/
stQCDTOT         private consumption
stQGDTOT         government consumption
stQEDTOT         enterprise consumption
stQINVTOT        investment consumption
stQABSORP        absorption
stIMPORT         import demand
stEXPORT         export supply
stGDP            GDP
stGDPVA          GDP from value added
stGDPEXP         GDP from expenditure
stSUPPLY         total domestic production
stUSE            total intermediate inputs
stYHTOT          household income
stYGTOT          government income
stYFTOT          factor income
stYFDISTTOT      distributed factor income
stYFDISPTOT      disposable income
stYFLABTOT       labour factor income
stTOTSAV         total savings
stHOSAV          household savings
stGOVSAV         government savings
stFSAV           foreign savings
stDEPREC         depreciation
stMTAX           Import tariff revenue
stETAX           Export tax revenue
stVTAX           VAT revenue
stSTAX           Sales tax revenue
stITAX           Indirect tax revenue
stFTAX           Factor tax revenue
stFYTAX          Factor income tax
stDTAX           Direct tax
stINTAX          Intermediate input tax
stTOTTAX         Total tax income
/
stab2        results tab 2
/stIMPregFOB     Imports valued fob by region shares
stIMPcomFOB      Imports valued fob by commodity shares
stIMPregCIF      Imports valued cif by region shares
stIMPcomCIF      Imports valued cif by commodity shares
stIMPregDOM      Imports valued at domestic prices by region shares
stIMPcomDOM      Imports valued at domestic prices by commodity shares
stEXPregFOB      Exports valued fob by region shares
stEXPcomFOB      Exports valued fob by commodity shares
stEXPregDOM      Exports valued at domestic prices by region shares
stEXPcomDOM      Exports valued at domestic prices by commodity shares
stSmImpSh        Small Import shares by commodity shares
stSmExpSh        Small Export shares by commodity shares
/

stab3        results tab 3
/stPRIVregDEM    private domestic demand by total domestic demand
stPRIVcomDEM     private domestic demand by total commodity demand
stGOVTregDEM     government domestic demand by total domestic demand
stGOVTcomDEM     government domestic demand by total commodity demand
stINVDregDEM     investment domestic demand by total domestic demand
stINVDcomDEM     investment domestic demand by total commodity demand
stINTDregDEM     intermediate domestic demand by total domestic demand
stINTDcomDEM     intermediate domestic demand by total commodity demand
stMAKEcomSUP     domestic make by commodity shares
stSUPPcomSUP     total domestic supply by commodity shares
stQMcomSUP       aggregate import supply by commodity shares
stQDcomSUP       domestic output to domestic market by commodity shares
stQEconSUP       domestic ouptut to export market by commodity shares
/

stab4        results tab 4
/stQINTQX         shares of intermediate input in GO by activity
stQINT           shares of intermediate input use by activity
StVAQX           shares of value added in GO by activity
stVA             shares of value added by activity
stQX             shares of gross output by activity
stLAB            shares of labour income in value added
stUskLAB         shares of unskilled labour income in value added
stSkLAB          shares of semi skilled labour income in value added
stSekLAB         shares of skilled labour income in value added
stCAP            shares of capital income in value added
stLND            shares of land income in value added
stFTAX           factor use taxes or subsidies in value added
stFACTchk        CHECK on factor shares addition
stSUB            If subsitution possible at Level 1
stELASTX         Elasticity of subsitution at Level 1
stELASTVA        Elasticity of subsitution at Level 2
stFSUB           Share of subsidies over production
/

stab5            results tab 4
/stTRANS         Transactions values in models
stACTSH          Factor mix by activity
stFFSH           Factor use by factor
/

welfDim        welfare dimension
/Deflat        Deflator
evTotal        Total
evHEXP        Household Expenditure
evqcdconstTot        Total Subsistence consumption
evQCD        Consumption
evqcdconst        Subsistence consumption
evYH        HH Income
evTYH        Income Tax
evSHH        Saving Rate
evHOHOout        Transfers paid to other HHs
evINSVA        Factor Income
evINSVATotal        Total Factor income
evHOHOHin        Trasnfers from other HHs
evHOENTin        Trasnfers from Enterprises
evHOGOVin        Trasnfers from Government
evHOROWin        Trasnfers from ROW
evYFINS        Factor income payment to HHs
evgovvash        Governmet factor income
evworvash        ROW facto rincome
evYFDISP        Factor income after depreciation
evdeprec        Depreciation
evTYF        Factor income tax
evYF        Factor Income net of Tax
evFDxWF        Factor income before tax
evfactwor
/

agBudgEl
/
Recurr  Recurrent
Invest  Investment
InpSub  Input Subsidies
OutSub  Output Subsidies
ComSub  Commodity Subsidy
IncSub  Income Subsidy

Total   Total
Share   Share in government budget
/

ghgElem1
/
 Total
 Households
 Activities
/

ghgElem2
/
 NaN
 Total          Total emissions
 Intermediate   Inputs-related emissions
 Output         Output-relatade emissions
 Endowment      Endowment-related emissions
/

ghgElem3
/
 Total
 Combustion
 Non-combustion-all-exclLULUCF
 Non-combustion-process
 Non-combustion-fossil
/


;
