$TITLE DEMETRA Population Accumulation parameter declarations
*------------------------------------------------------------------------------
*-------------------------------------------------------------------------------
*--   DEMETRA v1.0-alpha
*--
*--   GAMS file : calibchk_declare.inc
*--
*--   @purpose  : Declares the parameters for capital update
*--   @author   :
*--   @date     :
*--   @since    :
*--   @refDoc   :
*--   @seeAlso  :
*--   @calledBy : dynamic simulations
*-------------------------------------------------------------------------------
*-------------------------------------------------------------------------------

$ontext
Notes and description



$offtext

*------- 1. Declare and Assign Parameters  ------------------------

*---- 1a. Declare Parameters for Capital Accumulation

Parameter

Trk_birthp(h,sim,t)
Trk_popchngp(h,sim,t)
Trk_popnp(h,sim,t1)

;
