"""Reusable GAMS text templates for SML-generated models."""

HEADER_TEMPLATE = """* Generated by Signal Modelling Language
* GAMS is a modelling language and execution environment.
* Solver engines such as PATH, CONOPT, and IPOPT perform numeric computation.
"""

MODEL_FOOTER_TEMPLATE = """Model {model_name} / all /;
Solve {model_name} using CNS;
Display {display_symbols};
execute_unload "{gdx_path}";
"""


def solver_option_block(solver: str) -> str:
    selected = solver.lower()
    if selected in {"path", "conopt", "ipopt"}:
        return f"option nlp={selected};\noption mcp={selected};"
    return "* Default GAMS solver selection is used."
